query {
  headerContent {
    bannerImage {
      url
      height
      width
    }
    title_en
    title_pt
    description_en
    description_pt
    backgroundColor
    header_action_text_en
    header_action_text_pt
    header_action_link
    menu {
      id
      description_en
      description_pt
      icon_name
      order
      path
      hash
    }
  }
}
