query Work($id: ID!) {
  work(id: $id) {
    id # Or _id if you are using MongoDB
    name_en
    name_pt
    role_en
    role_pt
    details_en
    details_pt
    link
    backgroundColor
    categories {
      description_en
      description_pt
    }
    technologies {
			name
      svgIcon
    }
    mobile_mockup_image {
      url
      height
      width
    }
		web_mockup_image {
      url
      height
      width
    }
  }
}