query Work($id: ID!) {
  work(id: $id) {
    id # Or _id if you are using MongoDB
    name_en
    name_pt
    problem_en
    problem_pt
    repository
    backgroundColor
    categories {
      description_en
      description_pt
    }
    technologies {
			name
      svgIcon
    }
    mockup_image {
      url
      height
      width
    }
		thumbnail {
      url
      height
      width
    }
    mobile_images {
      url
      height
      width
    }
    images {
      url
      height
      width
    }
    project_period
    team_size
    happy_customers
  },
}