query Work($id: ID!) {
  work(id: $id) {
    id
    details
    name
    image {
    	url
      width
      height
    },
    link
    backgroundColor
    categories {
      description
    }
    technologies {
      description
    }
    
  }
}